<section class=advertisement>
    <h3>For Those About To Code (We Salute You)</h3>
    <ul>
        <li>We roll tonight to the keyboard byte</li>
        <li>Stand up and be counted for what you are about to receive</li>
        <li>We are the dealers</li>
        <li>We'll give you everything you need</li>
        <li>Hail hail to the good times</li>
        <li>Cos code has got the right of way</li>
        <li>We ain't no legends ain't no cause</li>
        <li>We're just livin' for today</li>
        <li>For those about to code, we salute you</li>
        <li>For those about to code, we salute you</li>
    </ul>
</section>
