<!DOCTYPE html>
<html lang='pl'>
{{head/singleArticle}}
<body id='start' class='blog'>
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.10';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
{{topBar}}
{{header}}
<div class='container'>
    {{articleMenu}}
    <div class='wrapper'>
        {{main}}
        {{aside}}
    </div><!--.wrapper-->
    {{footer/last}}
</div>
{{goTop/param}}
</body>
</html>

