<main class="main-contact" itemprop="mainContentOfPage" itemscope="" itemtype="http://schema.org/Blog">
        {{logo}}
        <h2 class='describe'>Formularz kontaktowy</h2>
        <form>
            <input type='text' placeholder='full name'>
            <div class="row">
                <input type='text' placeholder='phone number'>
                <input type='text' placeholder='email'>
            </div>
            <textarea placeholder='The place one can write to trzczy'></textarea>
            <input type='submit' value='OK'>
        </form>
    {{close}}
</main>