<nav class='top-bar' itemscope itemtype="http://schema.org/SiteNavigationElement">
    <h2 class="visually-hidden">Menu główne</h2>
    <ul class='top-menu'>
        <li><a href="./">Intro</a></li>
        <li><a href="?ctrl=blog">Blog</a></li>
        <li><a href="#">About</a></li>
        <li><a href="?ctrl=apps">Apps</a></li>
        <li><a href="?ctrl=contact">Contact</a></li>
    </ul>
</nav>